Added messages rating(unstable), and running on GPU....
ParisNeo/Gpt4All-webui pull request #10
Opened 2023-04-04 01:14 UTC by Jiankun-Huang

Colab for running on GPU:
https://cdn.discordapp.com/attachments/1070838609051144212/1092617824494698628/gpt4all_gpu.ipynb

Rest of the code is a RUFT DRAFT!!

2023-04-04 05:35 UTC, ParisNeo commented
Thanks. I'll look it up this evening (european time).

2023-04-04 07:22 UTC, ParisNeo requested changes
We need to make GPU usage optional.
You can add a command line option to select CPU or GPU (using argparse)

You are specifying the model path directly in the code. This is not possible. The user needs to be able to download and use the model. In the next version I am going to be using the new python bindings to this, so you may just keep it as it was until I finish this migration this evening (western european time).

I also prefer keeping the character by character function as it is way more user friendly. I'll take care of adding the message to the discussion when it ends.

If you want, just keep the old streaming way:
```
                bot = self.chatbot_bindings.bot
                bot.stdin.write(message.encode('utf-8'))
                bot.stdin.write(b"\n")
                bot.stdin.flush()

                # Segmented (the user receives the output as it comes)
                return Response(stream_with_context(self.parse_to_prompt_stream()))
```                
And keep the CPU version as I'm going to do a big update this evening on which you can build. GPU will be an option in command line.

Thank you for your help.

2023-04-04 14:30 UTC, Jiankun-Huang commented
Specifying is gpu is simple, can do later

2023-04-04 14:35 UTC, Jiankun-Huang commented
I can keep the old streaming too

2023-04-05 06:55 UTC, ParisNeo commented
Can you please update your code so that I can merge it.
Consider keeping the GPU part as We are moving to a new python binding library maybe tomorrow
Best regards

2023-04-05 14:25 UTC, ParisNeo reviewed
Please adress the issues reviewed in this pull request

2023-04-05 14:25 UTC, ParisNeo commented on static/js/chat.js
> +Note:This is a beta demo of GPT4All.
I need this to stay, I'll be moving it to a special section for examples

2023-04-05 22:25 UTC, Jiankun-Huang commented
Okay

2023-04-07 05:15 UTC, ParisNeo commented
Hi there,

The project moved to nomic-ai's repo: https://github.com/nomic-ai/gpt4all-ui

Please use that repo from now on as this one will not be the official version.

I have made an issue about adding a ranking system there. If you want to contribute feel free to create a fork on that repo.

Best regards

2023-04-07 05:16 UTC, closed without merging